

drahtlosesensoren.pdf: drahtlosesensoren.tex webserver.tex block1.pdf
	pdflatex drahtlosesensoren.tex </dev/null
	pdflatex drahtlosesensoren.tex </dev/null

block1.pdf: block1.eps
	epstopdf block1.eps

view:
	evince drahtlosesensoren.pdf &
